name: CI

on:
  push:
    branches: ["**"]

jobs:
  Build-on-Ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install System dependencies
        run: |
          sudo apt update
          sudo apt install python3 socat

      - name: Install Python dependencies
        run: |
          sudo apt install python3-pytest python3-serial python3-pexpect

      - name: Run tests
        run: |
          python3 -m pytest tests/test_pyterm.py
